image: php:7.4

stages:
  - build
  - test
  - deploy

before_script:
  # Set php.ini configuration
  - mv php.ini-dev "$PHP_INI_DIR/php.ini"
  - apt-get update -yqq
  - apt-get install -yqq libzip-dev libpng-dev unzip
  # Install PHP extensions
  - docker-php-ext-install zip gd sockets
  # Run Composer
  - php composer.phar --version
  - php -d memory_limit=-1 composer.phar install

unitaire:
  stage: test
  script:
    - vendor/bin/phpunit

linter_back:
  stage: test
  script:
    - vendor/bin/php-cs-fixer fix --dry-run -vv